  # Freeze Tag Configuration
  # ======================
  # 
  # HEURISTIC MODE NOTES:
  # - When agents are in heuristic mode (BehaviorType = HeuristicOnly), the YAML parameters below are ignored
  # - Instead, the manual configuration values in the Inspector are used:
  #   * manualRunnerCount, manualTaggerCount, manualFoodballCount, manualFreezeBallCount, manualGameTimeLimit
  #   * manualLevelIndex (0 = Level 1, 1 = Level 2) determines which level is active
  #   * isLevel2 property is based on levelIndex (isLevel2 = levelIndex == 1)
  # - To use manual testing mode:
  #   1. Set agents' BehaviorParameters to "Heuristic Only"
  #   2. Configure all parameters in the FreezeTagController inspector
  #


  behaviors:
    RunnerBehavior: # Matches 'Behavior Name' in RunnerAgent's Behavior Parameters component
      trainer_type: ppo
      hyperparameters:
        batch_size: 1024
        buffer_size: 10240
        learning_rate: 3.0e-4
        beta: 5.0e-3
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
      network_settings:
        normalize: false
        hidden_units: 256  # Increased from 128 to 256
        num_layers: 3      # Increased from 2 to 3
        vis_encode_type: simple # Use simple if only using Raycasts; change if using CameraSensor
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 1.0
      max_steps: 1000000 # Total training steps
      time_horizon: 64
      summary_freq: 10000
      keep_checkpoints: 0 # Save checkpoints periodically

    TaggerBehavior: # Matches 'Behavior Name' in TaggerAgent's Behavior Parameters component
      trainer_type: ppo
      hyperparameters:
        batch_size: 512 # Might need smaller batch if fewer taggers
        buffer_size: 5120
        learning_rate: 3.0e-4
        beta: 5.0e-3
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
      network_settings:
        normalize: false
        hidden_units: 256  # Increased from 128 to 256
        num_layers: 3      # Increased from 2 to 3
        vis_encode_type: simple
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 1.0
      max_steps: 1000000 # Train tagger for same duration
      time_horizon: 64
      summary_freq: 10000
      keep_checkpoints: 0

  # Environment parameters for curriculum learning
  environment_parameters:
    lesson: # This is the master curriculum parameter that controls progression
      curriculum:
        - name: Lesson0 # Level 1 - Basic Collection Game
          completion_criteria:
            measure: reward
            behavior: RunnerBehavior
            min_lesson_length: 100
            threshold: 0.5
            require_reset: true
          value: 0.0 
        - name: Lesson1 # Level 2 - Freeze Tag Game
          value: 1.0
    
    # All other parameters are determined by the current lesson
    level_index:
      sampler_type: constant
      sampler_parameters:
        value: 0.0 # Default Level 1
      curriculum_remapping:
        - lesson: 1.0 # When in Lesson1
          value: 1.0 # Level 2
    
    num_foodballs:
      sampler_type: constant
      sampler_parameters:
        value: 10.0 # Same for both levels
    
    num_runners:
      sampler_type: constant
      sampler_parameters:
        value: 5.0 # Same for both levels
    
    num_taggers:
      sampler_type: constant
      sampler_parameters:
        value: 0.0 # No taggers in Level 1
      curriculum_remapping:
        - lesson: 1.0 # When in Lesson1
          value: 2.0 # 2 taggers in Level 2
    
    num_freezeballs:
      sampler_type: constant
      sampler_parameters:
        value: 0.0 # No freeze balls in Level 1
      curriculum_remapping:
        - lesson: 1.0 # When in Lesson1
          value: 5.0 # 5 freeze balls in Level 2
    
    time_limit:
      sampler_type: constant
      sampler_parameters:
        value: 100.0 # Long time limit for Level 1
      curriculum_remapping:
        - lesson: 1.0 # When in Lesson1
          value: 60.0 # Shorter time limit for Level 2