behaviors:
  RunnerBehavior:
    trainer_type: ppo
    behavioral_cloning:
      demo_path: demos/RunnerDemo  # Folder with multiple .demo files
      strength: 0.5                # Moderate imitation strength
      steps: 500000                # Apply BC loss for first 500k steps
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0  # Full reliance on environment rewards once BC phase ends
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 20000
    checkpoint_interval: 40000
    keep_checkpoints: 250

environment_parameters:
  lesson:
    sampler_type: constant
    sampler_parameters:
      value: 1.5  # Lesson value

  level_index:
    sampler_type: constant
    sampler_parameters:
      value: 1.0  # Level index

  num_foodballs:
    sampler_type: constant
    sampler_parameters:
      value: 10.0  # Number of foodballs

  num_runners:
    sampler_type: constant
    sampler_parameters:
      value: 5.0  # Number of runners

  num_taggers:
    sampler_type: constant
    sampler_parameters:
      value: 2.0  # Number of taggers

  num_freezeballs:
    sampler_type: constant
    sampler_parameters:
      value: 10.0  # Number of freezeballs

  time_limit:
    sampler_type: constant
    sampler_parameters:
      value: 90.0  # Time limit for each episode
